# Generated by Django 3.0.4 on 2020-04-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_linerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerecord',
            name='recordCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
