# Generated by Django 3.0.4 on 2020-04-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_linerecord_recordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerecord',
            name='recordDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
