# Generated by Django 3.0.4 on 2020-04-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0005_auto_20200419_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linerecord',
            name='recordDate',
        ),
    ]
